= Apache JMeter on Openshift
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2021-04
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
// End: Enable admonition icons

This repository helps you to deploy the latest version of JMeter on Openshift taking advantage of RH UBI images and Openshift resources.

// Create the Table of contents here
toc::[]

== Introduction

The https://jmeter.apache.org/[Apache JMeter™] application is open source software, a 100% pure Java application designed to load test functional behavior and measure performance. It was originally designed for testing Web Applications but has since expanded to other test functions.

== JMeter on your laptop: Building the container image

In order to perform some testing locally, you may want to build the JMeter image directly on your laptop. 

[source, bash]
----
podman build -t localhost/jmeter:latest ./container-image
----

== JMeter on your laptop: Running the image


[source, bash]
----
podman run --rm -it --name jmeter localhost/jmeter:latest
----




== JMeter on Openshift: Building the container image


If your have a disconnected Openshift installation, you will also require to build your application locally.

[source, bash]
----
APP_NAMESPACE="jmeter"
GIT_REPOSITORY="https://github.com/alvarolop/jmeter-on-ocp.git"
oc new-project $APP_NAMESPACE --display-name="JMeter Testing" --description="This namespace contains resources to deploy JMeter"

oc process -f templates/jmeter-bc.yaml -p APP_NAMESPACE=$APP_NAMESPACE -p GIT_REPOSITORY=$GIT_REPOSITORY | oc apply -f -

----


== JMeter on Openshift: Deploying the image


First, create a ConfigMap that will store your application configuration:
[source, bash]
----
TEST="example"
oc create configmap jmeter-config -n $APP_NAMESPACE \
--from-file=${TEST}.jmx=tests/${TEST}/test.jmx \
--from-file=config.properties=tests/config.properties
----

[source, bash]
----
oc process -f templates/jmeter-dc.yaml -p APP_NAMESPACE=$APP_NAMESPACE | oc apply -f -

----

== JMeter on Openshift: Obtaining JMeter reports

[source, bash]
----
# Get JMeter pod name
JMETER_POD=$(oc get pods -l app=jmeter -n $APP_NAMESPACE --template='{{(index .items 0).metadata.name}}')
NOW=$(date +"%Y-%m-%d_%H-%M")
mkdir ./results/$NOW-$TEST
oc rsync $JMETER_POD:/opt/jmeter/results/$TEST-report/* ./results/$NOW-$TEST
----



== Useful links


* Official https://jmeter.apache.org/usermanual/get-started.html[Apache JMeter documentation].
* Medium: https://medium.com/chaya-thilakumara/start-learning-jmeter-with-sample-test-cases-2dc2a4963b62[Start Learning JMeter With Sample Test Cases].








== Annex: Running jmeter in your laptop

[source, bash]
----
JMETER_BASE=$(pwd)
TEST_PLAN=test-01
NOW=$(date +"%Y-%m-%d_%H-%M")
jmeter -n -p "$JMETER_BASE/tests/${TEST_PLAN}/config.properties" -t "$JMETER_BASE/tests/${TEST_PLAN}/jmeter-test-plan.jmx" -l "$JMETER_BASE/results/${NOW}-${TEST_PLAN}.jtl" -e -o "$JMETER_BASE/results/${NOW}-${TEST_PLAN}-report"
----