= Apache JMeter on Openshift
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2021-04
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
// End: Enable admonition icons

This repository helps you to deploy the latest version of JMeter on Openshift taking advantage of RH UBI images and Openshift resources.

// Create the Table of contents here
toc::[]

== Introduction

The https://jmeter.apache.org/[Apache JMeter™] application is open source software, a 100% pure Java application designed to load test functional behavior and measure performance. It was originally designed for testing Web Applications but has since expanded to other test functions.

== JMeter on your laptop: Building the container image

In order to perform some testing locally, you may want to build the JMeter image directly on your laptop. 

[source, bash]
----
podman build -t localhost/jmeter:latest ./container-image
----

== JMeter on your laptop: Running the image


[source, bash]
----
podman run --rm -it --name jmeter localhost/jmeter:latest
----




== JMeter on Openshift: Building the container image






== Building the container image on Openshift
If your have a disconnected Openshift installation, you will also require to build your application locally.

[source, bash]
----
JMETER_NAMESPACE="jmeter"
oc new-project $JMETER_NAMESPACE --display-name="JMeter Testing" --description="This namespace contains resources to deploy JMeter"
----


== JMeter on Openshift: Deploying the image


First, create a ConfigMap that will store your application configuration:
[source, bash]
----
oc create configmap ${app_name}-config \
--from-file=application.properties=src/main/resources/application-k8s.properties \
--from-file=logback-spring.xml=src/main/resources/logback-spring-k8s.xml -n $namespace
----

[source, bash]
----

----

== JMeter on Openshift: Obtaining JMeter reports

[source, bash]
----

----



== Useful links
