apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jmeter
  annotations:
    description: Template to build a JMeter container image to test applications on OCP.
    tags: java,jmeter
    iconClass: icon-rh-openjdk
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
labels:
  template: jmeter
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
      namespace: ${APP_NAMESPACE}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
      namespace: ${APP_NAMESPACE}
    spec:
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:v1
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: ${GIT_CONTEXT_DIR}
        git:
          ref: main
          uri: ${GIT_REPOSITORY}
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: ubi8-openjdk-11:1.3
            namespace: openshift
        type: Dockerfile
      failedBuildsHistoryLimit: 2
      successfulBuildsHistoryLimit: 1
      triggers:
      - type: ConfigChange
      - type: ImageChange
parameters:
  - name: APPLICATION_NAME
    description: "The name of the Image stream (output)."
    required: false
    value: "jmeter"
  - name: APP_NAMESPACE
    description: "The namespace where the BuildConfig will be executed."
    required: true
  - name: GIT_CONTEXT_DIR
    description: "The sub-directory where the source code for the application exists."
    value: "container-image"
    required: false
  - name: GIT_REPOSITORY
    description: "The uri of the source that will be built. It should contain a Dockerfile under GIT_CONTEXT_DIR"
    required: true
